version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
  groups:
    default:
      patterns:
        - "*"
      exclude-patterns:
        - "pyo3"
    python-bindings:
      patterns:
        - "pyo3"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  groups:
    default:
      patterns:
        - "*"
